### ISSUE TITLE
AGProgressDialog Dismiss exception

### ISSUE THREAD

**Issue by cvasquez-github** [NinevaStudios/android-goodies-docs-PRO#10]
AGProgressDialog.Dismiss() crashes the app if the object was already dismissed.
I would recommend to include some validation on the _dialog object before calling dismiss to prevent that issue, ideally with a try/catch statement, maybe something like this:

`if (_dialog == null || _dialog.GetRawObject().ToInt32() == 0)
            {
                Debug.Log("Can't dismiss spinner -> null object");
            }
            else
            {
                AGUtils.RunOnUiThread(() =>
                {
                   try
                    {
                        _dialog.Call("dismiss");
                        _dialog.Dispose();
                    }
                    catch (Exception e)
                    {
                        Debug.Log("Exception dismissing Dialog:" + e.Message);
                    }
                });
            }`

**Comment by TarasOsiris** [comment]
Thanks for reporting this, we will have a look, also a recommended approach would be to just keep a boolean flag in the calling script to avoid calling JNI methods twice anyways

**Comment by cvasquez-github** [comment]
Thanks Taras
