### ISSUE TITLE
AGGallery : Picking picture from gallery app always returns error (Invalid Image)

### ISSUE THREAD

**Issue by Sami-AlEsh** [NinevaStudios/android-goodies-docs-PRO#13]
Code:
AGGallery.PickImageFromGallery(OnImagePicked_Android, errorMessage => Debug.Log("Picking image Cancelled: " + errorMessage),shouldGenerateThumbnails: false);

Also if Image size is big (2 or 3 MB) app is crashed.

**Comment by TarasOsiris** [comment]
Hello, are you using the latest version from the store? Please update to the latest version and make sure you have the access to external storage permission. Also please Can you please also provide some logcat logs if not?

**Comment by Sami-AlEsh** [comment]
Nope i'm using an old version ,I will update the package soon and check it again.
Thanks for quick response :)

**Comment by Sami-AlEsh** [comment]
Issue fixed in latest version, Thanks !

**Comment by TarasOsiris** [comment]
@Sami-AlEsh You are welcome. Also please write us a review on the asset store if you enjoy the plugin and support, it will help us a lot, thanks
