### ISSUE TITLE
"Invalid image" returned from AGGallery.PickImageFromGallery

### ISSUE THREAD

**Issue by kobush** [NinevaStudios/android-goodies-docs-PRO#3]
This works fine with the default demo app, and I can select the same image. Code is exactly the same so not sure what can cause this. Taking photos with camera works just fine.

**Comment by TarasOsiris** [comment]
Most likely caused by misconfigured provider in manifest https://github.com/NinevaStudios/android-goodies-docs-PRO/wiki/AGGallery.cs#setup
