### ISSUE TITLE
Camera/gallery functions don't work on samsung devices

### ISSUE THREAD

**Issue by SlimeQ** [NinevaStudios/android-goodies-docs-PRO#4]
Both affected devices are newer Samsung devices with virtual navigation bars

- Android 8.0 and 8.1.0
- Samsung Experience 9.0 and 9.5

I first attempted to just copy the sample code for opening the gallery/camera into my app. This works fine on my older Samsung devices, but on the newer ones with a virtual navigation bar the app just freezes and the virtual navigation/status bars are shown. If I hit the back button on the navigation bar, it returns to the app but a message comes up saying that it failed.

Next I attempted to just run the sample scene, and I get a black screen on all devices. This may be due to something wrong with my project, but I do not know what.

**Comment by TarasOsiris** [comment]
Hello,

Please check the setup part, I am pretty sure you missed the provide package replacement part: https://github.com/TarasOsiris/android-goodies-docs-PRO/wiki/AGShare.cs#setup

**Comment by SlimeQ** [comment]
That worked, thanks. I didn't even know there was a setup guide
