### ISSUE TITLE
AGAlertDialog.ShowMessageDialog triggers App Paused / Focused

### ISSUE THREAD

**Issue by cvasquez-github** [NinevaStudios/android-goodies-docs-PRO#5]
Hello,
Is there a way to prevent AGAlertDialog.ShowMessageDialog triggering OnApplicationPause()/OnApplicationFocus() events in Unity Android projects?

**Comment by TarasOsiris** [comment]
Hello,

No, unfortunately not, it is standard Android behavior, showing the dialog makes activity being paused resulting in onPause() Android method call and Unity invokes OnApplicationPause()/OnApplicationFocus()

**Comment by cvasquez-github** [comment]
Wow, that was fast, thank you very much Taras for your immediate response!
Is there any flag or global variable that we could query to know if there is a MessageDialog currently being displayed? (that way we could differentiate the action we take onPause()). AGAlertDialog.ShowMessageDialog does not return an object (void) so I don't see a direct way to do that. If not we might need to implement a flag on our side, to detect if the Pause/Focus commands was actually triggered by AG.

**Comment by TarasOsiris** [comment]
I guess it would be the easiest solution to just set a boolean before showing the dialog and re-setting when you receive the callback
