### ISSUE TITLE
AGCalendar crashs calendar App from Samsung

### ISSUE THREAD

**Issue by GrazianoGiuseppe** [NinevaStudios/android-goodies-docs-PRO#6]
Hi, i have tested the example code on a Samsung S8.
The calendar will open but without any visible ui. Only store and cancel is visible.
After some seconds the calendar app crashs.

Any ideas? thx

**Comment by TarasOsiris** [comment]
Hello, yeah, I have experienced something like this with samsung calendar before, this is because it does not properly support some properties. I suggest you starting with just plain event with name and time and start adding properties until you see which one actually crashes the app.

**Comment by GrazianoGiuseppe** [comment]
thx that works!

**Comment by TarasOsiris** [comment]
@GrazianoGiuseppe Awesome!

Also please write us a review on Asset Store if you enjoy the plugin and the support of course, it will help me a lot, thanks.
