### ISSUE TITLE
Camera SetUp Issue

### ISSUE THREAD

**Issue by aashish9810** [NinevaStudios/android-goodies-docs-PRO#8]
hello i have done all the necessary step to use camera, but still i am getting a toast "cancelled taking photos from camera ", pick photo from gallery is working fine. Please help

**Comment by TarasOsiris** [comment]
You need to request runtime camera permission to use it, please check AGPermissions in the docs

**Comment by TarasOsiris** [comment]
@aashish9810 https://github.com/NinevaStudios/android-goodies-docs-PRO/wiki/AGPermissions.cs
