### ISSUE TITLE
Crash on picking image from downloads

### ISSUE THREAD

**Issue by nitishmehta3** [NinevaStudios/android-goodies-docs-PRO#9]
Run your "Goodies Demo" app present on play store, pick image from downloads folder, then app crashes. Note, open downloads from "Open From" not from inside of "Images" folder.

**Comment by TarasOsiris** [comment]
Hi @nitishmehta3, this issue is fixed in the package on asset store, just didn't update the demo on Google Play

**Comment by nitishmehta3** [comment]
Oh, Cool. Will try that!!

**Comment by TarasOsiris** [comment]
fixed
